%% LaBGAS_3_spm_diagnose_firstlvl_models
%
% This script runs diagnosis on first level analysis generated by 
% LaBGAS_2_spm_fit_firstlvl_models.m for Nathalie's emotional modulation 
% of visceral pain/SERT study
% IT IS MADE TO BE CALLED FROM THE PREVIOUS SCRIPT RATHER THAN FOR
% STANDALONE USE
%__________________________________________________________________________
%
% authors: 
% lukas.van.oudenhove@dartmouth.edu, lukas.vanoudenhove@kuleuven.be
% bogdan.petre@dartmouth.edu,
% marta.ceko@colorado.edu
%
% date:   October, 2020
%
%__________________________________________________________________________
% @(#)% LaBGAS_3_spm_diagnose_firstlvl_models.m         v1.0        
% last modified: 2020/10/20
%
%% settings
% addpath(genpath('C:\Users\lukas\Documents\GitHub\CanlabCore')); % add relevant CANlab tools folders and spm to Matlab path if they are not there yet - I have saved them on my Matlab path permanently hence do not need this
% addpath(genpath('C:\Users\lukas\Documents\GitHub\CanlabPrivate'));
% addpath(genpath('C:\Users\lukas\Documents\MATLAB\spm12'));

DSGN = LaBGAS_get_firstlvl_dsgn_obj(); % calls function to write DSGN structure array to your Matlab workspace

sid = DSGN.subjects{i}(end-5:end);
logDir=[DSGN.modeldir, '\', sid, '\diagnostics'];
cd(logDir);

vifs = scn_spm_design_check([DSGN.modeldir, '\', sid],'events_only');
save('vifs','vifs');